/* A packrat parser generated by PackCC 1.3.1 */

#ifndef PCC_INCLUDED_DIALOGO_H
#define PCC_INCLUDED_DIALOGO_H

void init();
void final();

struct Array {int size; int len; char** data;};

void array_init(struct Array *array, int size);
void array_free(struct Array *array);
char* array_add(struct Array *array, char* str);
char* array_get(struct Array *array, int idx);
int array_contains(struct Array *array, char* str);

const int D_NORDEST = 3;
const int D_NORDOVEST = 11;
const int D_NORD = 2;
const int D_GIU = 6;
const int D_FUORI = 7;
const int D_SUDEST = 5;
const int D_SUDOVEST = 9;
const int D_SUD = 8;
const int D_SU = 0;
const int D_DENTRO = 1;
const int D_EST = 4;
const int D_OVEST = 10;

void print_start();
void print_final();
void print_ident();
void _printf(const char* fmt, ...);
void print_room(char* name);
void print_supporter(char* name, int mobile);
void print_container(char* name, int mobile);
void print_object(char* name);
void print_item(char* name);
void print_handled(char* name);
void print_wearable(char* name);
void print_female(char* name);
void print_edible(char* name);
void print_openable(char* name);
void print_open(char* name);
void print_close(char* name);
void print_is_in(char* name, char* loc);
void print_is_on(char* name, char* loc);
void print_descr(char* name, char* str);
void print_look(char* name, char* str);
void print_fromto(int dir, char* locfrom, char* locto);
void print_fromtoandback(int dir, char* locfrom, char* locto);
void print_instead_of(char* azione, char* obj1, char* obj2);
void print_plaintext(char* str);


#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(void *auxil);
int pcc_parse(pcc_context_t *ctx, char **ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_DIALOGO_H */
